server:
  port: 8080
spring:
  datasource:
    # 使用druid数据源
    url: jdbc:mysql://172.23.76.13:3306/spring?useUnicode=true&characterEncoding=UTF-8
    username : root
    password : 3.1415926
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fzy.springboot.pojo  # 注意：对应实体类的路径